apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- es-cert.yaml
- externalsecret.yaml
- elasticsearch-vpa.yaml
- networkpolicy.yaml
- pvc-es.yaml
- service.yaml
- serviceaccount.yaml
- statefulset.yaml
- setup-user-job.yaml

namespace: mastodon

patches:
- target:
    group: batch
    version: v1
    kind: Job
    name: elasticsearch-setup-mastodon-user
  patch: |-
    - op: replace
      path: /metadata/name
      value: elasticsearch-setup-mastodon-user
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: elasticsearch-master
  path: elasticsearch-priority-patch.yaml
