apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mastodon

resources:
  - migrate-job.yaml
  - svc.yaml
  - web-deployment.yaml
  - web-hpa.yaml
  - web-vpa.yaml
  - web-pdb.yaml

patches:
- path: web-priority-patch.yaml
- path: web-spread-patch.yaml
- target:
    group: batch
    version: v1
    kind: Job
    name: mastodon-db-migrate
  patch: |-
    - op: replace
      path: /metadata/name
      value: mastodon-db-migrate
