apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mastodon

configMapGenerator:
  - name: mastodon-core-env
    literals:
      - RAILS_ENV=production
      - NODE_ENV=production
      - TZ=Europe/Stockholm
      - SINGLE_USER_MODE=false
      - MASTODON_USE_LIBVIPS=true
      - RAILS_LOG_TO_STDOUT=true
      - PREPARED_STATEMENTS=false

  - name: mastodon-db-env
    literals:
      - DB_HOST=mastodon-postgresql-pooler
      - DB_PORT=5432
      - DB_NAME=mastodon
      - DB_SSLMODE=require
      - DB_SSLROOTCERT=/opt/mastodon/.postgresql/root.crt
      - DB_POOL=15
      - REPLICA_DB_HOST=mastodon-postgresql-repl
      - REPLICA_DB_PORT=5432
      - REPLICA_DB_NAME=mastodon
      - REPLICA_PREPARED_STATEMENTS=false
      - REPLICA_DB_TASKS=false
      - DATABASE_TIMEOUT=60
      - STREAMING_DATABASE_TIMEOUT=10

  - name: mastodon-cache-env
    literals:
      - REDIS_HOST=mastodon-redis-master
      - REDIS_PORT=6379
      - REDIS_URL=redis://mastodon-redis-master:6379/0
      - SIDEKIQ_REDIS_URL=redis://mastodon-redis-master:6379/1
      - CACHE_REDIS_URL=redis://mastodon-redis-master:6379/2
      - STREAMING_REDIS_URL=redis://mastodon-redis-master:6379/3
      - QUERY_CACHE_REDIS_URL=redis://mastodon-redis-master:6379/4
      - SIDEKIQ_CONCURRENCY=15

  - name: mastodon-search-env
    literals:
      - ES_ENABLED=true
      - ES_HOST=https://elasticsearch-master
      - ES_PORT=9200
      - ES_USER=mastodon
      - ES_PRESET=single_node_cluster
      - ES_SSL=true
      - ES_CA_FILE=/opt/mastodon/.elasticsearch/ca.crt

  - name: mastodon-metrics-env
    literals:
      - MASTODON_PROMETHEUS_EXPORTER_ENABLED=true
      - MASTODON_PROMETHEUS_EXPORTER_LOCAL=true

  - name: mastodon-features-env
    literals:
      - MAX_TOOT_CHARS=1500
      - FETCH_REPLIES_ENABLED=true
      - FETCH_REPLIES_COOLDOWN_MINUTES=15
      - FETCH_REPLIES_INITIAL_WAIT_MINUTES=5
      - FETCH_REPLIES_MAX_GLOBAL=1000
      - FETCH_REPLIES_MAX_SINGLE=500
      - FETCH_REPLIES_MAX_PAGES=500
      - IP_RETENTION_PERIOD=15552000

  - name: mastodon-network-env
    literals:
      - PORT=3000
      - BIND=0.0.0.0
      - RAILS_SERVE_STATIC_FILES=true
      - WEB_CONCURRENCY=2
      - MAX_THREADS=5
      - STREAMING_API_BASE_URL=wss://goingdark.social
      - STREAMING_PORT=4000

  - name: mastodon-storage-env
    literals:
      - S3_ENABLED=true
      - S3_BUCKET=mastodata
      - S3_ALIAS_HOST=cdn.goingdark.social
      - S3_PROTOCOL=https
      - S3_REGION=auto
      - S3_PERMISSION=
      - EXTRA_MEDIA_HOSTS=https://cdn.goingdark.social

  - name: mastodon-smtp-env
    literals:
      - SMTP_DELIVERY_METHOD=smtp
      - SMTP_AUTH_METHOD=login
      - SMTP_SSL=false
      - SMTP_TLS=false
      - SMTP_ENABLE_STARTTLS_AUTO=true
      - SMTP_OPENSSL_VERIFY_MODE=peer

  - name: mastodon-translate-env
    literals:
      - DEFAULT_LOCALE=en
      - ALLOWED_PRIVATE_ADDRESSES=127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
      - LIBRE_TRANSLATE_ENDPOINT=http://libretranslate.libretranslate.svc:5000

resources:
  - namespace.yaml
  - secretstore.yaml
  - serviceaccount.yaml
  - externalsecret.yaml
