apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: mastodon-web-vpa
  namespace: mastodon
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mastodon-web
  updatePolicy:
    updateMode: "Initial"
  resourcePolicy:
    containerPolicies:
      - containerName: web
        minAllowed: { cpu: "200m", memory: "256Mi" }
        maxAllowed: { cpu: "1000m", memory: "1Gi" }