apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cryptpad
  namespace: cryptpad
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: local-path
