apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: libretranslate-keys
  namespace: libretranslate
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 128Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: libretranslate-local
  namespace: libretranslate
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 10Gi
