apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: mastodon-postgresql
  namespace: mastodon
spec:
  teamId: "mastodon"
  volume:
    size: 10Gi
  numberOfInstances: 2
  users:
    mastodon:
      - superuser
      - createdb
  databases:
    mastodon: mastodon
  enableLogicalBackup: false
  postgresql:
    version: "17"
    parameters:
      archive_timeout: "300"
  patroni:
    initdb:
      - encoding: UTF8
      - data-checksums
      - locale: C
      - lc-collate: C
      - lc-ctype: C

  spiloFSGroup: 103
  tls:
    secretName: mastodon-postgresql-server
    caSecretName: mastodon-postgresql-ca
    caFile: ca.crt

  enableConnectionPooler: true
  enableReplicaConnectionPooler: true
  connectionPooler:
    numberOfInstances: 2
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

  envFrom:
    - secretRef:
        name: mastodon-walg-s3
    - configMapRef:
        name: mastodon-backup-env
