apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mastodon-walg-s3
  namespace: mastodon
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-backend
  target:
    name: mastodon-walg-s3
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
        AWS_ENDPOINT: "{{ .AWS_ENDPOINT }}"
        WAL_S3_BUCKET: "{{ .WAL_S3_BUCKET }}"
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: app-mastodon-s3-access-key
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: app-mastodon-s3-secret-key
    - secretKey: AWS_ENDPOINT
      remoteRef:
        key: app-mastodon-s3-endpoint-url
    - secretKey: WAL_S3_BUCKET
      remoteRef:
        key: app-mastodon-pg-backup-bucket
